services:
  frontend:
    build: .
    container_name: nuxt-gaffs
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    networks:
      - nuxtnet

networks:
  nuxtnet:
    driver: bridge
